---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: kube-system
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
      app.kubernetes.io/instance: headlamp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headlamp
        app.kubernetes.io/instance: headlamp
    spec:
      containers:
        - name: headlamp
          securityContext:
            privileged: false
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 100
          image: "ghcr.io/headlamp-k8s/headlamp:latest"
          imagePullPolicy: Never
          args:
            - "-in-cluster"
            - "-enable-dynamic-clusters"
            - "-kubeconfig=/home/headlamp/.config/Headlamp/kubeconfigs/config"
          ports:
            - name: http
              containerPort: 4466
              protocol: TCP
          env:
            - name: KUBECONFIG
              value: "/home/headlamp/.config/Headlamp/kubeconfigs/config"
          volumeMounts:
            - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/
              name: kubeconfig-volume
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
        - name: kubeconfig-volume
          hostPath:
            path: /home/runner/.kube/config
            type: File
